[package]
name = "sway-action"
version = "0.1.7"
authors = ["Rouven Czerwinski <rouven@czerwinskis.de>"]
edition = "2018"

[dependencies]
clap = "2"
failure = "0.1.8"
shellexpand = "2.0.0"

[dependencies.i3ipc]
path = "i3ipc-rs"
features = ["sway-1-1"]
